### ISSUE TITLE
IWD2_EET.tp2 making Items usable in Paused Game

### ISSUE THREAD

**Issue by WeareTheDraiken** [The-Gate-Project/IWD2_EET#14]
There seems to be these lines in IWD2_EET.tp2: 

```
APPEND ~instant.ids~ ~160 ApplySpellRES(S:RES*,O:Target)~ UNLESS ~ApplySpellRES~
APPEND ~instant.ids~ ~34 UseItem(S:Object*,O:Target*)~    UNLESS ~UseItem~
APPEND ~instant.ids~ ~230 RestParty()~                    UNLESS ~^230~
```

This adds "
 UseItem(S:Object*,O:Target*)" to the Instant.IDS file, making it possible to use potions, item effects and somtimes wands (the usage of wands not being consistent) when the game is paused indefinitely per round without inpausing the game.

Like some kind of atwill timestop for item usage.

I don't know if this was on purpose, but it's very chessy and I think it needs to be addressed.

As for a temporary solution, I removed the "UseItem(S:Object*,O:Target*)" line manually with a Text editor and it got rid of the issue entirely.

**Comment by 11jo** [comment]
Hello !

I saw your discussion on discord, I don't know either if it's on purpose.

It's not easy to reach Tipun lately, but will ask when possible.

Since we don't know if UseItem as a purpose, I can't remove it just like that wihout more insight.

Anyway thanks for reporting here it will be useful when Tipun's back !

**Comment by 11jo** [comment]
Hello @WeareTheDraiken, 

`APPEND ~instant.ids~ ~34 UseItem(S:Object*,O:Target*)~    UNLESS ~UseItem~`

Has been reverted by Tipun in the [last commit](https://github.com/The-Gate-Project/IWD2_EET/commit/17219c87d8e1829e47e2468d1f35d469d60838e3#diff-967ba743d9952e7f90daea3530a857cf5c22ce44930ae0566f62723abda03e27).
